# Generated by Django 4.2.5 on 2023-10-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_cart_quantity_alter_payment_amount_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cam', 'Camera'), ('Wm', 'WashingMachine'), ('Hea', 'Headphone'), ('Lap', 'Laptop'), ('Fan', 'Fan'), ('Tel', 'Television'), ('Mob', 'Mobiles'), ('Fri', 'Fridge'), ('Fur', 'Furniture'), ('Gro', 'Grocery'), ('sho', 'Shoes')], max_length=20),
        ),
    ]
