# Generated by Django 4.2.5 on 2023-10-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
