# Generated by Django 4.2.5 on 2023-10-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
