# Generated by Django 4.2.5 on 2023-10-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
