# Generated by Django 4.2.5 on 2023-10-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_orderplaced_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
