# Generated by Django 4.2.5 on 2023-10-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
