# Generated by Django 4.2.5 on 2024-01-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_customer_country_customer_country_not_null'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='locality_not_null',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='Address',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('Address__isnull', False)), name='Address_not_null'),
        ),
    ]
