# Generated by Django 4.2.5 on 2024-01-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_country_state_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
