# Generated by Django 4.2.5 on 2024-01-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_remove_state_country_delete_city_delete_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
