# Generated by Django 4.2.5 on 2024-03-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('category1', 'Category 1'), ('category2', 'Category 2')], max_length=20),
        ),
    ]
