# Generated by Django 4.2.5 on 2024-03-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_contactmessage_admin_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='admin_reply',
            field=models.TextField(blank=True),
        ),
    ]
