# Generated by Django 4.2.5 on 2024-03-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_remove_review_product_remove_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
