# Generated by Django 4.2.5 on 2024-03-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_orderplaced_delivered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='delivered_date',
        ),
    ]
