# Generated by Django 4.2.5 on 2024-04-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='mobile',
            field=models.IntegerField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='username',
            field=models.CharField(default='', max_length=25),
        ),
    ]
