# Generated by Django 4.2.5 on 2024-04-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
